# Generated by Django 4.0.4 on 2022-04-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showrunner", "0004_team_stats_alter_conference_logo_alter_team_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="stats",
        ),
    ]
