# Generated by Django 4.0.4 on 2022-04-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showrunner', '0005_remove_team_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='School',
        ),
    ]
