# Generated by Django 4.0.4 on 2022-04-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showrunner", "0007_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="website",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="stats",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
