# Generated by Django 4.0.4 on 2022-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showrunner", "0010_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="stats",
            field=models.JSONField(null=True),
        ),
    ]
