# Generated by Django 4.0.4 on 2022-04-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrunner', '0015_player_uniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
