# Generated by Django 4.0.4 on 2022-04-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showrunner', '0016_player_hometown_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='player',
            name='high_school',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('uniform', 'team')},
        ),
    ]
